// curated icon set for shortcuts, quick links, and the status line.
// stored in config as the kebab-case name; add here to extend the picker.
import {
	Globe,
	Mail,
	Calendar,
	SquareCheckBig,
	Inbox,
	MessageCircle,
	Phone,
	Camera,
	Film,
	Music,
	Headphones,
	Gamepad2,
	Code,
	Terminal,
	Briefcase,
	BookOpen,
	Newspaper,
	Bookmark,
	Heart,
	Star,
	Zap,
	Coffee,
	Brain,
	Target,
	Rocket,
	Plane,
	Car,
	Dumbbell,
	Wallet,
	ChartLine,
	ShoppingCart,
	House,
	GitBranch,
	CirclePlay,
	Image,
	Hash,
	AtSign,
	Tv
} from '@lucide/svelte';
import type { Component } from 'svelte';

export const ICONS: Record<string, Component<{ size?: number | string }>> = {
	globe: Globe,
	mail: Mail,
	calendar: Calendar,
	'square-check-big': SquareCheckBig,
	inbox: Inbox,
	'message-circle': MessageCircle,
	phone: Phone,
	camera: Camera,
	film: Film,
	music: Music,
	headphones: Headphones,
	'gamepad-2': Gamepad2,
	code: Code,
	terminal: Terminal,
	briefcase: Briefcase,
	'book-open': BookOpen,
	newspaper: Newspaper,
	bookmark: Bookmark,
	heart: Heart,
	star: Star,
	zap: Zap,
	coffee: Coffee,
	brain: Brain,
	target: Target,
	rocket: Rocket,
	plane: Plane,
	car: Car,
	dumbbell: Dumbbell,
	wallet: Wallet,
	'chart-line': ChartLine,
	'shopping-cart': ShoppingCart,
	house: House,
	'git-branch': GitBranch,
	'circle-play': CirclePlay,
	image: Image,
	hash: Hash,
	'at-sign': AtSign,
	tv: Tv
};

export const ICON_NAMES = Object.keys(ICONS);
